### ISSUE TITLE
ngx-print does not take color to the print screen ( when you add a background-color to HTML/CSS) it does not show on the printed sheet

### ISSUE THREAD

**Issue by Fordknox** [selemxmn/ngx-print#39]
**Describe the bug**
background-color does not pull through to the printed sheet

**To Reproduce**
add a background color to your CSS file, or even inline on your HTML

**Expected behavior**
Background color is displayed when you want to print ( example background color is blue) 

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows 10.
 - Browser chrome.
 - Version Version 74.0.3729.169 (Official Build) (64-bit)

**Additional context**

**Comment by sezmars** [comment]
@Fordknox 
Hi.
You can try this https://github.com/sezmars/angular-print.
See the demo.

**Comment by AhsanAyaz** [comment]
@Fordknox , you can use the below styles:

```scss
* {
  outline: none;
  color-adjust: exact;
  -webkit-print-color-adjust: exact;
  print-color-adjust: exact;
}

This should include the background colors as well for the print
```
